export const GATE_TARGET_SAMPLE_RATE = 16000
export const GATE_TARGET_DURATION_MS = 2000
export const GATE_TARGET_SAMPLE_COUNT =
  (GATE_TARGET_SAMPLE_RATE * GATE_TARGET_DURATION_MS) / 1000

export const FRAME_MS = 20
export const FRAME_SIZE = (GATE_TARGET_SAMPLE_RATE * FRAME_MS) / 1000

export const FLATLINE_ABS_MAX_THRESHOLD = 0.001
export const FLATLINE_RMS_THRESHOLD = 0.003
export const TOO_QUIET_RMS_THRESHOLD = 0.008
export const BORDERLINE_QUIET_RMS_THRESHOLD = 0.015

export const SPEECH_FRAME_RMS_THRESHOLD = 0.015
export const NO_SPEECH_RATIO_THRESHOLD = 0.1
export const PASS_SPEECH_RATIO_THRESHOLD = 0.2

export const CLIP_LEVEL = 0.98
export const CLIP_RATIO_THRESHOLD = 0.002

export const LATE_START_MS = 1400
export const EARLY_END_MS = 600
export const MIN_SPEECH_SPAN_MS = 350
